# Generated by Django 4.2.7 on 2024-02-29 23:31

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.profile_picture_directory),
        ),
    ]
