# Generated by Django 4.2.7 on 2024-02-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
